# Generated by Django 5.2.15 on 2026-07-05 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.CharField(blank=True, db_index=True, max_length=254)),
                ('action', models.CharField(choices=[('LOGIN', 'Logged in'), ('LOGOUT', 'Logged out'), ('LOGIN_FAILED', 'Login failed'), ('PASSWORD_CHANGED', 'Password changed'), ('API_TOKEN_ISSUED', 'API token issued'), ('INVITATION_SENT', 'Invitation sent'), ('INVITATION_ACCEPTED', 'Invitation accepted'), ('INVITATION_CANCELLED', 'Invitation cancelled'), ('USER_CREATED', 'User created'), ('USER_UPDATED', 'User updated'), ('USER_ROLE_CHANGED', 'User role changed'), ('USER_ACTIVATED', 'User activated'), ('USER_DEACTIVATED', 'User deactivated'), ('JOB_CREATED', 'Job created'), ('JOB_UPDATED', 'Job updated'), ('JOB_STATUS_CHANGED', 'Job status changed'), ('JOB_ASSIGNED', 'Job assigned'), ('JOB_UNASSIGNED', 'Job unassigned'), ('JOB_COMMENTED', 'Job comment added'), ('JOB_ATTACHMENT_ADDED', 'Job attachment added'), ('JOB_ATTACHMENT_DELETED', 'Job attachment deleted'), ('JOB_DELETE_ATTEMPTED', 'Job delete attempted'), ('JOB_DELETED', 'Job deleted'), ('SCHEDULE_CREATED', 'Scheduled task created'), ('SCHEDULE_UPDATED', 'Scheduled task updated'), ('SCHEDULE_PAUSED', 'Scheduled task paused'), ('SCHEDULE_RESUMED', 'Scheduled task resumed'), ('SCHEDULER_EXECUTED', 'Scheduler run executed'), ('OCCURRENCE_COMPLETED', 'Task occurrence completed'), ('SETTING_CHANGED', 'System setting changed'), ('CATEGORY_CHANGED', 'Job category changed'), ('DEPARTMENT_CHANGED', 'Department changed'), ('EXPORT_GENERATED', 'Export generated')], db_index=True, max_length=40)),
                ('object_type', models.CharField(blank=True, db_index=True, max_length=60)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=40)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('changes', models.JSONField(blank=True, help_text='Per-field before/after values: {"field": [before, after]}', null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='audits_audi_object__41d238_idx')],
            },
        ),
    ]
