# Generated by Django 5.2.15 on 2026-07-05 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerLock',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('action', models.CharField(choices=[('CREATE_OCCURRENCE', 'Create task occurrence (checklist item)'), ('CREATE_JOB', 'Create a full job / work order')], default='CREATE_OCCURRENCE', max_length=30)),
                ('frequency', models.CharField(choices=[('ONCE', 'One time'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('INTERVAL', 'Custom interval')], default='DAILY', max_length=10)),
                ('time_of_day', models.TimeField(blank=True, help_text='Run time for daily/weekly/monthly schedules.', null=True)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='For weekly schedules.', null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, help_text='1–28, for monthly schedules.', null=True)),
                ('interval_minutes', models.PositiveIntegerField(blank=True, help_text='Every N minutes (minimum 5), for custom intervals.', null=True)),
                ('starts_at', models.DateTimeField(help_text='First moment the schedule may run.')),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('job_priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('job_due_days', models.PositiveSmallIntegerField(default=3, help_text='Job due date = run time + this many days.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('FINISHED', 'Finished')], db_index=True, default='ACTIVE', max_length=10)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('assignees', models.ManyToManyField(blank=True, limit_choices_to={'role': 'STAFF'}, related_name='scheduled_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('job_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.jobcategory')),
                ('job_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.department')),
                ('job_manager', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['SUPER_ADMIN', 'MANAGER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('team_department', models.ForeignKey(blank=True, help_text='Assign to every active staff member of this department.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_tasks', to='core.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchedulerRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('PARTIAL', 'Completed with errors'), ('FAILED', 'Failed')], default='RUNNING', max_length=10)),
                ('triggered_by', models.CharField(choices=[('COMMAND', 'Management command / cron'), ('MANUAL', 'Manual (dashboard)')], default='COMMAND', max_length=10)),
                ('tasks_processed', models.PositiveIntegerField(default=0)),
                ('occurrences_created', models.PositiveIntegerField(default=0)),
                ('jobs_created', models.PositiveIntegerField(default=0)),
                ('occurrences_missed', models.PositiveIntegerField(default=0)),
                ('jobs_marked_overdue', models.PositiveIntegerField(default=0)),
                ('due_soon_notices', models.PositiveIntegerField(default=0)),
                ('errors_count', models.PositiveIntegerField(default=0)),
                ('log', models.TextField(blank=True)),
                ('triggered_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed')], db_index=True, default='PENDING', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_occurrences', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_occurrences', to='operations.job')),
                ('scheduled_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='scheduling.scheduledtask')),
            ],
            options={
                'ordering': ['-scheduled_for'],
                'constraints': [models.UniqueConstraint(fields=('scheduled_task', 'scheduled_for', 'assigned_to'), name='uniq_occurrence_per_assignee'), models.UniqueConstraint(condition=models.Q(('assigned_to__isnull', True)), fields=('scheduled_task', 'scheduled_for'), name='uniq_occurrence_unassigned')],
            },
        ),
    ]
