# Generated by Django 5.2.15 on 2026-07-05 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('JOB_ASSIGNED', 'Job assigned'), ('JOB_REASSIGNED', 'Job reassigned'), ('JOB_DUE_SOON', 'Job due soon'), ('JOB_OVERDUE', 'Job overdue'), ('JOB_SUBMITTED', 'Job submitted for review'), ('JOB_APPROVED', 'Job approved'), ('JOB_REJECTED', 'Job rejected'), ('TASK_DUE', 'Scheduled task due'), ('TASK_MISSED', 'Scheduled task missed'), ('SCHEDULER_FAILURE', 'Scheduler failure'), ('INVITATION_ACCEPTED', 'Invitation accepted'), ('WELCOME', 'Welcome'), ('SYSTEM', 'System')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, help_text='In-app path this notification links to.', max_length=300)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='notificatio_user_id_8a7c6b_idx')],
            },
        ),
    ]
